### ISSUE TITLE
Request about the work

### ISSUE THREAD

**Issue by ghost** [zcx88886666/Robot-Arm#1]
Hi, sorry to trouble you. I found that you had created an issue about reproducing the work of “Cross-media Structured Common Space for Multimedia Event Extraction”. Actually, I’m confused about the evaluation. In addition, it seems there are some missing files, e.g., "/voa_anno_m2e2/article_event.json”. If convenient for you, would you like to discuss about the work with me? Thank you very much.

**Comment by baoqianyue** [comment]
@YorickZilin，Hi，I would like to ask if you have obtained the image_event.json and article_event.json files in m2e2, can you share them with me, thank you very much.
